# Generated by Django 4.0.1 on 2022-01-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
