# Generated by Django 4.0.1 on 2022-01-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathtutor',
            name='img',
            field=models.ImageField(default='SOME STRING', upload_to='upload/'),
        ),
    ]
