# Generated by Django 4.0.1 on 2022-01-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_mathtutor_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathtutor',
            name='doc',
            field=models.FileField(default='SOME STRING', upload_to='upload/'),
        ),
    ]
