# Generated by Django 4.0.1 on 2022-01-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_mathtutor_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathtutor',
            name='dis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mathtutor',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
