# Generated by Django 4.0.1 on 2022-01-24 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0006_alter_mathtutor_matutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=1, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mathtutor',
            name='matutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mathtutor',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.sub'),
        ),
    ]
