# Generated by Django 4.0.1 on 2022-01-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_alter_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
