# Generated by Django 4.0.1 on 2022-01-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathtutor',
            name='subject',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.sub'),
        ),
    ]
