# Generated by Django 4.0.1 on 2022-01-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_mathtutor_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathtutor',
            name='img',
            field=models.ImageField(default='SOME stirng', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='mathtutor',
            name='subject',
            field=models.ForeignKey(blank=True, default='some string', on_delete=django.db.models.deletion.CASCADE, to='tutor.sub'),
        ),
    ]
