# Generated by Django 4.0.1 on 2022-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_alter_mathtutor_img_alter_mathtutor_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathtutor',
            name='doc',
            field=models.FileField(default='SOME string', upload_to='upload/'),
        ),
    ]
