# Generated by Django 4.0.1 on 2022-02-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0015_alter_mathtutor_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathtutor',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Userrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingbyuser', models.FloatField(default=0.0)),
                ('matutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.mathtutor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
